# Generated by Django 4.2.7 on 2023-11-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("musicapp", "0005_auto_20200712_1306"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="recent",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
